server:
  port: 8089

sampleservice:
  ribbon:
    DeploymentContextBasedVipAddresses: crudoperations
    ReadTimeout: 10000
    MaxAutoRetries: 2

hystrix:
  command:
    RemoteMessageClientCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    RemoteMessageAnnotationClient:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000